version: 2

sources:
  - name: raw
    database: medical_warehouse
    schema: raw
    tables:
      - name: telegram_messages
      - name: yolo_detections

models:
  - name: stg_telegram_messages
    description: "Cleaned telegram messages"
    columns:
      - name: message_id
        tests:
          - not_null
  - name: stg_yolo_detections
    description: "Staged YOLO object detections"
    columns:
      - name: message_id
        tests:
          - not_null
